# Economic Analysis of Bitcoin

In [126]:
#Regression Analysis of Bitcoin
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import statsmodels.api as sm
url = r"C:\Users\Manan\OneDrive\Desktop\Research Paprs\Regression Analysis files\Bitcoin Analysis.xlsx"
df = pd.read_excel(url,index_col = 'Date', parse_dates = True)

In [127]:
df.head()

Bitcoin Pricing(USD)  3 (month) Treasury Bill Average         M2  \
Date                                                                           
2015-04-01                236.15                             0.03  12022.950   
2016-04-01                448.32                             0.29  12791.525   
2017-04-01               1347.89                             0.74  13589.025   
2018-04-01               9240.55                             1.70  14078.760   
2019-04-01               5350.73                             2.40  14628.160   

            Google Trends   
Date                        
2015-04-01               2  
2016-04-01               3  
2017-04-01               6  
2018-04-01              18  
2019-04-01              12

In [179]:
#Standardising Data 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
sc = StandardScaler()
X = df.iloc[:,1:]
Y = df.iloc[:,0]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,shuffle = False)
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [180]:
print(X_train)

            3 (month) Treasury Bill Average         M2  Google Trends 
Date                                                                  
2015-04-01                             0.03  12022.950               2
2016-04-01                             0.29  12791.525               3
2017-04-01                             0.74  13589.025               6
2018-04-01                             1.70  14078.760              18
2019-04-01                             2.40  14628.160              12
...                                     ...        ...             ...
2015-11-01                             0.02  12288.040               4
2016-11-01                             0.33  13190.750               4
2017-11-01                             1.07  13818.125              45
2018-11-01                             2.25  14242.100              14
2019-11-01                             1.65  15238.725              11

[88 rows x 3 columns]


In [181]:
print(X_test)

            3 (month) Treasury Bill Average         M2  Google Trends 
Date                                                                  
2020-11-01                             0.10  18950.400              23
2021-11-01                             0.05  21291.340              34
2022-11-01                             3.72  21398.425              26
2023-11-01                             5.34  20746.800              20
2015-10-01                             0.02  12158.000               3
2016-10-01                             0.29  13071.160               3
2017-10-01                             1.03  13744.220              22
2018-10-01                             2.13  14199.920               9
2019-10-01                             1.89  15108.375              12
2020-10-01                             0.11  18655.475              14
2021-10-01                             0.04  21064.900              35
2022-10-01                             3.13  21394.500              17
2023-1

In [176]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df[['Bitcoin Pricing(USD)','Google Trends ','M2']].corr()

Bitcoin Pricing(USD)  Google Trends         M2
Bitcoin Pricing(USD)              1.000000        0.656783  0.855774
Google Trends                     0.656783        1.000000  0.524952
M2                                0.855774        0.524952  1.000000

In [182]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score 

lr = LinearRegression()

a = lr.fit(X_train,Y_train)
yhat = lr.predict(X_test)
print(lr.intercept_)
print(lr.coef_)

-44224.28345792902
[-1366.1      3.46   227.15]


In [183]:

X_train = sm.add_constant(X_train)

 #Fit the regression model
model = sm.OLS(Y_train, X_train).fit()

 #Print the regression results
print(model.summary())


                             OLS Regression Results                             
Dep. Variable:     Bitcoin Pricing(USD)   R-squared:                       0.836
Model:                              OLS   Adj. R-squared:                  0.830
Method:                   Least Squares   F-statistic:                     142.4
Date:                  Sun, 07 Jul 2024   Prob (F-statistic):           7.66e-33
Time:                          15:40:06   Log-Likelihood:                -895.31
No. Observations:                    88   AIC:                             1799.
Df Residuals:                        84   BIC:                             1809.
Df Model:                             3                                         
Covariance Type:              nonrobust                                         
                                      coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------

## R Squared 

In [161]:
lr.score(X_train,Y_train)

0.8357244344581172

# Predicting Algorithms 


In [162]:

# Calculate R-squared score
r2 = r2_score(Y_test,yhat)
print("R-squared score on testing data:", r2)
yhat = lr.predict(X_test)
np.set_printoptions(precision = 2 )

# Convert Series to numpy array and reshape
yhat_np = yhat.reshape(len(yhat), 1)
Y_test_np = Y_test.reshape(len(Y_test), 1)

# Concatenate arrays horizontally
combined = np.concatenate((yhat_np, Y_test_np), axis=1)
print(combined)
mse = mean_squared_error(Y_test, yhat)
print("Mean Squared Error:", mse)

R-squared score on testing data: 0.6980671927814135
[[26413.81 19625.84]
 [37078.2  57005.43]
 [30617.79 17168.57]
 [24787.8  37712.75]
 [-1515.13   314.17]
 [ 1274.68   700.97]
 [ 6907.79  6468.4 ]
 [ 4028.39  6317.61]
 [ 8180.09  9199.58]
 [23335.62 13781.  ]
 [36535.74 61318.96]
 [29365.85 20495.77]
 [24111.77 34667.78]
 [-1876.23   236.06]
 [ 1061.48   609.73]
 [ 6551.98  4338.71]
 [ 4615.43  6625.56]
 [ 7648.88  8293.87]
 [22484.91 10784.49]
 [35076.46 43790.89]
 [31271.68 19431.79]
 [23557.86 26967.92]]
Mean Squared Error: 94342525.6623337


# Support Vector Regression

In [163]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

# Initialize the SVR model
svr = SVR(kernel='linear', C=100, gamma='scale')

# Train the SVR model on the scaled training data
svr.fit(X_train, Y_train)

# Make predictions using the testing set
yhat = svr.predict(X_test)
# Evaluate the model
print('SVR Metrics:')
print('Mean Squared Error:', mean_squared_error(Y_test, yhat))
print('R-squared:', r2_score(Y_test, yhat))


SVR Metrics:
Mean Squared Error: 216698813.72654188
R-squared: 0.30647944084546885


In [164]:
yhat = yhat.reshape(22,1)
Y_test = Y_test.reshape(22,1)
combined = np.concatenate((yhat, Y_test), axis=1)
print(combined)


[[13024.59 19625.84]
 [17836.1  57005.43]
 [20958.34 17168.57]
 [21007.65 37712.75]
 [  628.2    314.17]
 [ 2180.31   700.97]
 [ 6848.37  6468.4 ]
 [ 6739.86  6317.61]
 [ 8160.65  9199.58]
 [11258.48 13781.  ]
 [17669.28 61318.96]
 [18901.8  20495.77]
 [20580.95 34667.78]
 [  506.68   236.06]
 [ 2113.22   609.73]
 [ 6611.2   4338.71]
 [ 6929.69  6625.56]
 [ 8052.5   8293.87]
 [10779.86 10784.49]
 [16857.79 43790.89]
 [19064.87 19431.79]
 [20138.83 26967.92]]


In [165]:
intercept_svr = svr.intercept_
support_vectors_svr = svr.support_
dual_coefficients_svr = svr.dual_coef_
print(f"SVR Intercept: {intercept_svr}")
print(f"SVR Support Vectors: {support_vectors_svr}")
print(f"SVR Dual Coefficients: {dual_coefficients_svr}")

SVR Intercept: [9874.71]
SVR Support Vectors: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87]
SVR Dual Coefficients: [[-100. -100. -100.  100. -100. -100.  100.  100.  100. -100. -100. -100.
   100.  100.  100.  100.  100.  100.  100. -100. -100. -100. -100. -100.
   100.  100. -100.  100.  100. -100. -100.  100. -100.  100.  100.  100.
   100.  100. -100. -100. -100. -100.  100.  100.  100.  100. -100. -100.
  -100.  100.  100.  100.  100.  100.  100.  100. -100. -100. -100.  100.
  -100.  100. -100.  100. -100. -100. -100. -100. -100. -100.  100.  100.
   100.  100. -100. -100.  100. -100. -100.  100.  100.  100.  100. -100.
  -100. -100. -100. -100.]]


# Random Forest Regressor

In [166]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
# Example of initializing RandomForestRegressor
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)
rf_regressor.fit(X_train, Y_train)
y_pred = rf_regressor.predict(X_test)
# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(Y_test, y_pred)
print("Mean Squared Error:", mse)

# Calculate R-squared
r2 = r2_score(Y_test, y_pred)
print("R-squared:", r2)
print(y_pred)

Mean Squared Error: 31185831.27713503
R-squared: 0.9001932000776408
[30898.64 44430.92 23031.05 35210.46   286.61   617.38  7849.59  5763.
  7922.09 13941.31 44133.87 19229.89 34138.15   244.45   573.8   4698.29
  7036.07  7914.88 11715.73 45512.32 21269.61 34145.78]


In [167]:
y_pred = y_pred.reshape(22,1)
Y_test = Y_test.reshape(22,1)
combined = np.concatenate((y_pred, Y_test), axis=1)
print(combined)
feature_importances = rf_regressor.feature_importances_

print(f"Feature Importances: {feature_importances}")

[[30898.64 19625.84]
 [44430.92 57005.43]
 [23031.05 17168.57]
 [35210.46 37712.75]
 [  286.61   314.17]
 [  617.38   700.97]
 [ 7849.59  6468.4 ]
 [ 5763.    6317.61]
 [ 7922.09  9199.58]
 [13941.31 13781.  ]
 [44133.87 61318.96]
 [19229.89 20495.77]
 [34138.15 34667.78]
 [  244.45   236.06]
 [  573.8    609.73]
 [ 4698.29  4338.71]
 [ 7036.07  6625.56]
 [ 7914.88  8293.87]
 [11715.73 10784.49]
 [45512.32 43790.89]
 [21269.61 19431.79]
 [34145.78 26967.92]]
Feature Importances: [0.11 0.87 0.03]


# K Nearest Regressor

In [168]:
from sklearn.neighbors import KNeighborsRegressor
# Initialize KNN Regressor with a chosen number of neighbors (e.g., 5)
knn_regressor = KNeighborsRegressor(n_neighbors=3)

# Fit the model on the training data
knn_regressor.fit(X_train, Y_train)

KNeighborsRegressor(n_neighbors=3)

In [169]:
y_pred = knn_regressor.predict(X_test)

In [170]:
mse = mean_squared_error(Y_test, y_pred)
print("Mean Squared Error:", mse)

r2 = r2_score(Y_test, y_pred)
print("R-squared:", r2)


Mean Squared Error: 22115362.81006212
R-squared: 0.9292222300704684
